const cuerdasData = [
    { id: 1, name: "Sufix 832 Advanced Superline", brand: "Sufix", category: "Trenzado", condition: "popular", price: null, image: "img/imagenes cuerdas/SUFIX_832_ADVANCED_SUPERLINE_HERO.png", description: "Trenzado de 8 fibras Gore Performance con fibra HMPE. Resistencia y sensibilidad superiores para todo tipo de pesca." },
    { id: 2, name: "Sufix 8 Carrier Braid", brand: "Sufix", category: "Trenzado", condition: "new", price: null, image: "img/imagenes cuerdas/SUFIX_8CARRIER_BRAID_HERO.png", description: "Trenzado de 8 portadores de alta resistencia y bajo estiramiento. Ideal para jigging y pesca en profundidad." },
    { id: 3, name: "Sufix Nano Braid Nanofilament", brand: "Sufix", category: "Trenzado", condition: "new", price: null, image: "img/imagenes cuerdas/SUFIX_NANO_BRAID_NANOFILAMENT_HERO.png", description: "Trenzado ultrafino con construccion nanofilamento. Excepcional resistencia en diametro reducido para ultraligera." },
    { id: 4, name: "Sufix EGI X8 Braid 150m", brand: "Sufix", category: "Trenzado", condition: "popular", price: null, image: "img/imagenes cuerdas/egi-x8-braid-sufix-150m.jpeg", description: "Trenzado de 8 hilos especial para pesca a jigging. 150 metros, sensibilidad maxima para detectar tocadas sutiles." },
    { id: 5, name: "Sufix X8 Hot Yellow", brand: "Sufix", category: "Trenzado", condition: "new", price: null, image: "img/imagenes cuerdas/X8_Spool_HotYellow.png", description: "Trenzado X8 en llamativo color amarillo para maxima visibilidad. Alta resistencia y bajo estiramiento." },
    { id: 6, name: "Sufix Matrix Pro", brand: "Sufix", category: "Trenzado", condition: "popular", price: null, image: "img/imagenes cuerdas/MatrixPRO_0000.png", description: "Trenzado Matrix Pro en verde medianoche. Excelente relacion resistencia/diametro para pesca de fondo y trolling." },
    { id: 7, name: "Sufix DuraFlex Monofilamento", brand: "Sufix", category: "Monofilamento", condition: "popular", price: null, image: "img/imagenes cuerdas/DuraFlex_0000.png", description: "Monofilamento DuraFlex de alta resistencia al impacto y abrasion. Excelente para pesca en costa y rios." },
    { id: 8, name: "Sufix Supreme Monofilamento", brand: "Sufix", category: "Monofilamento", condition: "popular", price: null, image: "img/imagenes cuerdas/Supreme_0000.png", description: "Monofilamento premium Supreme con excelente resistencia al nudo y durabilidad en largas jornadas." },
    { id: 9, name: "Sufix XL Strong", brand: "Sufix", category: "Monofilamento", condition: "new", price: null, image: "img/imagenes cuerdas/XL-STRONG.png", description: "Monofilamento de alta resistencia para grandes capturas. Ideal para surfcasting y pesca de orilla." },
    { id: 10, name: "Sufix Key Lime IGFA", brand: "Sufix", category: "Monofilamento", condition: "new", price: null, image: "img/imagenes cuerdas/SUFIX_KEY_LIME_IGFA_0000.png", description: "Monofilamento certificado IGFA color verde lima. Para competiciones y pesca deportiva seria." },
    { id: 11, name: "Sufix 21 Super FC Fluorocarbono", brand: "Sufix", category: "Fluorocarbono", condition: "popular", price: null, image: "img/imagenes cuerdas/SUFIX_21_SUPER_FC_HERO.png", description: "Fluorocarbono 100% de alta densidad. Practicamente invisible bajo el agua, resistente a la abrasion." },
    { id: 12, name: "Sufix Invisiline Leader", brand: "Sufix", category: "Fluorocarbono", condition: "new", price: null, image: "img/imagenes cuerdas/SUFIX_INVISILINE_LEADER_HERO.png", description: "Lider de fluorocarbono de maxima transparencia. Para presentaciones discretas en aguas cristalinas de rio y lago." },
    { id: 13, name: "Sufix HX Myth Fluorocarbono", brand: "Sufix", category: "Fluorocarbono", condition: "new", price: null, image: "img/imagenes cuerdas/SUFIX_HX_MYTH_HERO_CLEAR.png", description: "Fluorocarbono de alta resistencia y sensibilidad. Resistente a la luz UV y quimicos para mayor durabilidad." },
    { id: 14, name: "Sufix Performance Lead Core", brand: "Sufix", category: "Leadcore", condition: "new", price: null, image: "img/imagenes cuerdas/Perf_LeadCore.png", description: "Linea de plomo leadcore para trolling en profundidad. Control de inmersion perfecto para señuelos en capa." },
    { id: 15, name: "Ragot Nylon Nacrita 100m", brand: "Ragot", category: "Monofilamento", condition: "popular", price: null, image: "img/imagenes cuerdas/nylon-nacrita-connected-100-metros-ragot.jpeg", description: "Nylon monofilamento Nacrita 100 metros. Resistente y suave, excelente para la pesca en rio y lago." },
    { id: 16, name: "Ragot Tortue Trident VX Force 150m", brand: "Ragot", category: "Monofilamento", condition: "new", price: null, image: "img/imagenes cuerdas/tortue-trident-vx-force-monofilament-150-m.jpeg", description: "Monofilamento Trident VX Force 150 metros de alta resistencia. Para pesca de mar y agua dulce." }
];